resources:
  repositories:
  - repository: self
    type: git
    ref: master
jobs:
- job: Job_1
  displayName: code checkout
  pool:
    name: Default
  steps:
  - checkout: self
    clean: true
    fetchTags: false
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      TargetFolder: $(build.artifactstagingdirectory)/Angular